# Puerto del servidor
server.port=8080

# Configuración de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:multasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración del proveedor de pagos activo
app.pagos.proveedor=wompi
app.pagos.pagosudes.url=http://localhost:9001/pagosudes/transacciones
app.pagos.wompi.url=http://localhost:9002/wompi/transactions

